FROM node:23.11.1

RUN echo "Creating working dir and copying files"
RUN mkdir /app
WORKDIR /app
COPY . .

RUN npm i
# RUN npm i npx
## Bundled now in npm

CMD ["npm", "run", "build-parcel"]