FROM node:22

RUN echo "Creating working dir and copying files"
RUN mkdir /app
WORKDIR /app
COPY . .

RUN apt-get update
RUN apt-get autoremove -y 
RUN apt-get autoclean -y
RUN apt-get upgrade

RUN npm i
RUN npm i npx

CMD ["npm", "run", "build-parcel"]